<?php
	$contents['home'] = array (
                        'content/home',
                        'Split Flap'
                      );
	$contents['airport'] = array (
                        'content/airport',
                        'Airport'
                      );
	$contents['flightboard'] = array (
                        'content/flightboard',
                        'Flightboard JS'
                      );
?>