/**
 * @author Christoph Kepler
 */

/**
 * Configuration of the flipper and intervall and shit. ^^
 */

var nid = [
	['INGENIEUR FUER VERFAHRENSTECHNIK','A','KOUR'],
	['PRAKTIKANT TECHNICAL SALES','B','DUS'],
	['WERKSTUDENT ENGINEERING: CABIN + CARGO','C','HAM'],
	['PRAKTIKUM IM BEREICH LEAN LOGISTICS','C','HAM'],
	['WERKSTUDENT: MATERIALIEN UND PROZESSE','C','BRE'],
	['ABSCHLUSSARBEIT: A400M FLUEGELMONTAGE','C','STAD'],
	['PRAKTIKUM: SPACE EXPLORATION','D','BRE'],
	['PRAKTIKUM: SIMUL. HINDERNISWARNSYSTEM','D','FDH'],
	['PRAKTIKUM: HIGH PERFORMANCE COMPUTING','D','ULM'],
	['FINAL THESIS: HIGH VOLTAGE DC NETWORK','E','HAM'],
	['DOKTORARBEIT: MIKROWELLENTECHNOLOGIEN','E','MUC'],
	['VIE: HELICOPTER TRAINING SIMULATION','F','MUC'],
	['PRAKTIKUM PROJEKTMANAGEMENT TIGER','F','DONW'],
	['PRAKTIKUM SIMULATION | SOFTWAREENTW.','F','MAN'],
	['PROJEKTINGENIEURE AERODYNAMIK','G','BUND'],
	['AUSBILDUNG ZUM INDUSTRIEMECHANIKER','H','WILD'],
	['JUNIOR VBA ENTWICKLER IN DER LUFTFAHRT','I','MAN'],
	['QUALIFIZIERUNG FLUGGERAETMECHANIKER','I','HAM'],
	['FACHHELFER LOGISTIK','I','DONW'],
	['PRAKTIKANT|DIPLOMAND AEROSPACE','J','MUC'],
	['PRAKTIKANT|IN SALES + MARKETING','K','FRA'],
	['JUNIOR SUPPLY CHAIN MANAGER ','L','HAM'],
	['DIPLOM-INGENIEUR LUFT- UND RAUMFAHRT','M','DRS'],
	['AUSBILDUNG TECHNISCHER PRODUKTDESIGNER','N','GERS'],
	['MINT: SPITZENFORSCH. ENERGIE + VERKEHR','O','BUND'],
	['WERKSTUDENT IM MANAGEMENT CONSULTING','P','BER'],
	['STUDENT. AUSHILFE KUNSTSTOFFFERTIGUNG','Q','DRS'],
	['PRAKTIKUM PROGRAMMMANAGEMEMENT A330 ','Q','DRS'],
	['BERUFSEINSTIEG KONSTRUKTIONSINGENIEUR','R','FDH'],
	['AUSBILDUNG TECHNISCHER ZEICHNER','S','BLAN'],
	['PRAKTIKUM: BETREUUNG FLUGSIMULATOREN','T','FRA'],
	['PRAKTIKANT INFLIGHT + CATERING','U','HAM'],
	['HIWI IM FORSCHUNGSPROJEKT AIRPORT2030','V','HAM'],
	['WISS. MITARBEITER SATELLITENTECHNIK','W','BER'],
	['PRAKTIKANT|IN IM BEREICH LOGISTIK','X','BUND'],
	['WERKSTUDENT: SATELLITENKOMMUNIKATION','Y','MUC'],
	['PRAKTIKUM UNTERNEHMENSENTWICKLUNG','Z','MUC'],
	['PRAKTIKUM IN DER PRODUKTION','Z','MUC'],
	['PROMOTIONSSTIPENDIUM:  TRAEGERRAKETEN','0','MUC'],
	['PRAKTIKANT ARBEITSVORBEREITUNG ','1','ARNS'],
	['TRAINEEPROGRAMM LUFTFAHRT KONSTRUKTION','2','BRE'],
	['PRAKTIKANT IM BEREICH QM SYSTEMS','3','NOR'],
	['PRAKTIKANT|BACHELOR TEILEFERTIGUNG','3','NOR'],
	['DIPLOM-, MASTER- ODER BACHELORARBEIT','4','FRA'],
	['WEITERBD. SERVICEFACHKRAFT LUFTVERKEHR','5','BER'],
	['INTERN: ALLIANCE + NETWORK DEVELOPMENT','6','FRA'],
	['PRAXISSTUDENT DESIGN FOR MANUFACTURING','7','BACK'],
	['PRAKT. RAUMFAHRT: MECHANISCHE EFFEKTE ','7','BACK'],
	['LUFTVERKEHRSKAUFMANN|-FRAU BERUFSBEGL.','8','BER'],
	['FORTBILDUNG AIRCRAFT MAINTEN. MECHANIC','8','BER'],
];

var flipperinterval;
var linenumbers = 11;
var offset = linenumbers;
var charnumber = 38;
var lineflipintervall = 11;
var completeflipintervall = 200;
